# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('case_number', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('type_crime', models.CharField(max_length=10)),
                ('arrested', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
